### PR TITLE
Remove one empty directory

### PR DESCRIPTION
**Pull request by szepeviktor**
@maries24 What do you think?

### CODE REVIEW

**Comment by simonrjones** [comment]
Thanks @szepeviktor - we are planning to re-organise the codebase and split out the Symfony MVC specific stuff into another repo. So simplifying folder names may be a good idea. 

I'll chat to the team about this suggestion when we work on this (hope to be in next month or so, pending summer holidays!)

**Comment by maries24** [comment]
@simonrjones Why not? It’s tidying things up and should not break the code, i.e. not a significant risk.
I’d be fine with it.
---
Marie Manandise
Senior Web Developer

Studio 24
Digital Design + Technology

www.studio24.net <https://www.studio24.net/>
01223 328017

**Comment by simonrjones** [comment]
I'll merge this into the refactoring branch, thanks for your contribution @szepeviktor

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
